"""
User Components and Protections
namespace: spiderucs

"""


from django.db import models
from django.conf import settings
from django.utils.translation import pgettext_lazy
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType


from jsonfield import JSONField

from .signals import test_success
from .protections import installed_protections


import logging

logger = logging.getLogger(__name__)

class UserComponent(models.Model):
    id = models.BigAutoField(primary_key=True, editable=False)
    name = models.SlugField(max_length=50, null=False)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)
    contents = None
    # should be used for retrieving active protections, related_name
    assigned = None
    protections = models.ManyToManyField("spiderucs.Protection", through="spiderucs.AssignedProtection")
    class Meta:
        unique_together = [("user", "name"),]
        indexes = [
            models.Index(fields=['user', 'name']),
        ]

    def __str__(self):
        return self.name

    def auth_test(self, request):
        for p in self.assigned.filter(can_test=True, active=True):
            if p.auth_test(request):
                return True
        return False

    def settings(self, request):
        pall = []
        for p in self.assigned.all():
            pall.append(p.settings(request))
        return pall
    def get_absolute_url(self):
        return reverse("spiderucs:uc-view", kwargs={"user":self.user.username, "name":self.name})


class UserContent(models.Model):
    usercomponent = models.ForeignKey(UserComponent, on_delete=models.CASCADE, editable=False, related_name="contents")

    #creator = models.ForeignKey(settings.AUTH_USER_MODEL, editable=False, null=True, on_delete=models.SET_ZERO)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)
    # for extra information over content, admin only editing
    info = models.TextField(null=False, default="")
    content_type = models.ForeignKey(ContentType, on_delete=models.CASCADE, editable=False)
    object_id = models.BigIntegerField(editable=False)
    content = GenericForeignKey('content_type', 'object_id', for_concrete_model=False)


class ProtectionManager(models.Manager):
    def invalid(self):
        return self.get_queryset().exclude(code__in=installed_protections)

    def valid(self):
        return self.get_queryset().filter(code__in=installed_protections)


# don't confuse with Protection objects used with add_protection
# this is pure DB
class Protection(models.Model):
    objects = ProtectionManager()
    # autogenerated, no choices required
    code = models.SlugField(max_length=10, primary_key=True)
    can_render = models.BooleanField(default=False)
    can_test = models.BooleanField(default=False)

    def __str__(self):
        return str(installed_protections[self.code])

class AssignedProtection(models.Model):
    id = models.BigAutoField(primary_key=True)
    protection = models.ForeignKey(Protection, on_delete=models.CASCADE, related_name="assigned", limit_choices_to={"code__in": installed_protections}, editable=False)
    usercomponent = models.ForeignKey(UserComponent, on_delete=models.CASCADE, editable=False)
    # data for protection
    protectiondata = JSONField(default={}, null=False)
    created = models.DateTimeField(auto_now_add=True, editable=False)
    modified = models.DateTimeField(auto_now=True, editable=False)
    active = models.BooleanField(default=True)
    class Meta:
        unique_together = [("protection", "usercomponent"),]

    #def get_absolute_url(self):
    #    return reverse("spiderucs:protection", kwargs={"user":self.usercomponent.user.username, "ucid":self.usercomponent.id, "pname": self.protection.code})

    def auth_test(self):
        return installed_protections[self.protection.code].auth_test(request=request, user=usercomponent.user, data=self.protectiondata, obj=self)

    def settings(self, request):
        if request.method == "GET":
            return installed_protections[self.protection.code](self.protectiondata, prefix=self.protection.code)
        else:
            prot = installed_protections[self.protection.code](request.POST, prefix=self.protection.code)
            if prot.is_valid():
                self.active = prot.cleaned_data.pop("active")
                self.protectiondata = prot.cleaned_data
                self.save()
            return prot

    def clean(self):
        installed_protections[self.protection.code].clean(self)
