# Generated by Django 2.1.4 on 2018-12-30 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spider_base', '0018_auto_20181230_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebConfig',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=800)),
                ('config', models.TextField(blank=True, default='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('usercomponent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webconfigs', to='spider_base.UserComponent')),
            ],
        ),
    ]
