# Generated by Django 2.1.4 on 2018-12-31 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebConfig',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=800)),
                ('config', models.TextField(blank=True, default='')),
            ],
            options={
                'abstract': False,
                'default_permissions': [],
            },
        ),
    ]
