# Generated by Django 3.0.1 on 2019-12-29 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0012_auto_20191229_2304'),
        ('spider_webcfg', '0004_auto_20191229_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WebConfig',
        ),
        migrations.CreateModel(
            name='WebConfig',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('spider_base.datacontent',),
        ),
    ]
