# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 20:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProtection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('protectiondata', jsonfield.fields.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('code', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('can_render', models.BooleanField(default=False)),
                ('can_test', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserComponent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('protections', models.ManyToManyField(through='spiderucs.AssignedProtection', to='spiderucs.Protection')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('info', models.TextField(default='')),
                ('object_id', models.BigIntegerField(editable=False)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('usercomponent', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='spiderucs.UserComponent')),
            ],
        ),
        migrations.AddField(
            model_name='assignedprotection',
            name='protection',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='spiderucs.Protection'),
        ),
        migrations.AddField(
            model_name='assignedprotection',
            name='usercomponent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='spiderucs.UserComponent'),
        ),
        migrations.AddIndex(
            model_name='usercomponent',
            index=models.Index(fields=['user', 'name'], name='spiderucs_u_user_id_1e1ecd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercomponent',
            unique_together=set([('user', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='assignedprotection',
            unique_together=set([('protection', 'usercomponent')]),
        ),
    ]
