# Generated by Django 2.0.5 on 2018-05-26 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderucs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponent',
            name='name',
            field=models.SlugField(help_text='\nName of the component.\nNote there are special named components\nwith different protection types and scopes.\nMost prominent: "index" for authentication\n'),
        ),
    ]
