# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderucs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='protection',
            name='can_render',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='assignedprotection',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
