# Generated by Django 2.0 on 2017-12-04 14:31

from django.db import migrations, models
import django.db.models.deletion
import spkbspider.apps.spider.models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderucs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomponent',
            name='deletion_requested',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='assignedprotection',
            name='protection',
            field=models.ForeignKey(editable=False, limit_choices_to={'code__in': spkbspider.apps.spider.models.ProtectionManager.valid}, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='spiderucs.Protection'),
        ),
    ]
