# Generated by Django 2.0.5 on 2018-05-06 16:01

from django.db import migrations, models
import django.db.models.deletion
import spkbspider.apps.spider.models
import spkbspider.apps.spider.protections


class Migration(migrations.Migration):

    dependencies = [
        ('spiderucs', '0002_auto_20171204_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protection',
            name='can_render',
        ),
        migrations.RemoveField(
            model_name='protection',
            name='can_test',
        ),
        migrations.AddField(
            model_name='protection',
            name='ptype',
            field=models.PositiveIntegerField(default=spkbspider.apps.spider.protections.ProtectionType(1)),
        ),
        migrations.AlterField(
            model_name='assignedprotection',
            name='protection',
            field=models.ForeignKey(editable=False, limit_choices_to=spkbspider.apps.spider.models.AssignedProtection.get_limit_choices, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='spiderucs.Protection'),
        ),
    ]
