# Generated by Django 2.0.5 on 2018-05-14 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderucs', '0003_auto_20180506_1601'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomponent',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='usercontent',
            options={'ordering': ['usercomponent', 'id']},
        ),
        migrations.AlterField(
            model_name='assignedprotection',
            name='usercomponent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='protected_by', to='spiderucs.UserComponent'),
        ),
    ]
