# Generated by Django 2.0.5 on 2018-06-06 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import spkcspider.apps.spider.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedProtection',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField(default={})),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Protection',
            fields=[
                ('code', models.SlugField(max_length=10, primary_key=True, serialize=False)),
                ('ptype', models.CharField(default='\x01', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserComponent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nonce', models.SlugField(default=spkcspider.apps.spider.models.token_nonce, max_length=20)),
                ('name', models.SlugField(help_text='\nName of the component.<br/>\nNote: there are special named components\nwith different protection types and scopes.<br/>\nMost prominent: "index" for authentication\n')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deletion_requested', models.DateTimeField(default=None, null=True)),
                ('protections', models.ManyToManyField(related_name='usercomponents', through='spider_base.AssignedProtection', to='spider_base.Protection')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserContent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('nonce', models.SlugField(default=spkcspider.apps.spider.models.token_nonce, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('deletion_requested', models.DateTimeField(default=None, null=True)),
                ('info', models.TextField(default=';', validators=[spkcspider.apps.spider.models.info_field_validator])),
                ('object_id', models.BigIntegerField(editable=False)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
        ),
        migrations.CreateModel(
            name='UserContentVariant',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('ctype', models.CharField(max_length=10)),
                ('code', models.CharField(max_length=255)),
                ('name', models.SlugField(max_length=255)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='usercontent',
            name='ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='spider_base.UserContentVariant'),
        ),
        migrations.AddField(
            model_name='usercontent',
            name='usercomponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='spider_base.UserComponent'),
        ),
        migrations.AddField(
            model_name='assignedprotection',
            name='protection',
            field=models.ForeignKey(editable=False, limit_choices_to=spkcspider.apps.spider.models.get_limit_choices_assigned_protection, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='spider_base.Protection'),
        ),
        migrations.AddField(
            model_name='assignedprotection',
            name='usercomponent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='protected_by', to='spider_base.UserComponent'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontentvariant',
            unique_together={('owner', 'name')},
        ),
        migrations.AddIndex(
            model_name='usercontent',
            index=models.Index(fields=['usercomponent'], name='spider_base_usercom_c9b782_idx'),
        ),
        migrations.AddIndex(
            model_name='usercontent',
            index=models.Index(fields=['object_id'], name='spider_base_object__ef74d9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercontent',
            unique_together={('content_type', 'object_id')},
        ),
        migrations.AddIndex(
            model_name='usercomponent',
            index=models.Index(fields=['user'], name='spider_base_user_id_3c1312_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='usercomponent',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='assignedprotection',
            index=models.Index(fields=['usercomponent'], name='spider_base_usercom_02174c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='assignedprotection',
            unique_together={('protection', 'usercomponent')},
        ),
    ]
