# Generated by Django 2.0.5 on 2018-05-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponent',
            name='protections',
            field=models.ManyToManyField(related_name='usercomponents', through='spider_base.AssignedProtection', to='spider_base.Protection'),
        ),
    ]
