# Generated by Django 2.0.5 on 2018-06-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usercomponent',
            options={},
        ),
    ]
