# Generated by Django 2.0.5 on 2018-06-10 14:54

from django.db import migrations, models
import spkcspider.apps.spider.models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='deletion_requested',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='info',
            field=models.TextField(editable=False, unique=True, validators=[spkcspider.apps.spider.models.info_field_validator]),
        ),
    ]
