# Generated by Django 2.0.5 on 2018-06-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protection',
            name='ptype',
            field=models.CharField(default='b', max_length=10),
        ),
    ]
