# Generated by Django 2.0.6 on 2018-06-12 01:16

from django.db import migrations, models
import spkcspider.apps.spider.models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('spider_base', '0002_auto_20180610_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercontent',
            name='info',
            field=models.TextField(editable=False, validators=[spkcspider.apps.spider.models.info_field_validator]),
        ),
        migrations.AlterUniqueTogether(
            name='usercontent',
            unique_together={('content_type', 'object_id'), ('usercomponent', 'info')},
        ),
    ]
