# Generated by Django 2.1 on 2018-08-12 18:55

import datetime
from django.db import migrations, models
import django.db.models.deletion
import spkcspider.apps.spider.models
from spkcspider.apps.spider.models import user


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0002_linkcontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('session_key', models.CharField(max_length=40, null=True)),
                ('token', models.SlugField(max_length=136)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='usercomponent',
            name='protections',
        ),
        migrations.AddField(
            model_name='usercomponent',
            name='token_duration',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
        migrations.AlterField(
            model_name='assignedprotection',
            name='usercomponent',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='protections', to='spider_base.UserComponent'),
        ),
        migrations.AlterField(
            model_name='usercomponent',
            name='required_passes',
            field=models.PositiveIntegerField(default=user._get_default_amount),
        ),
        migrations.AddField(
            model_name='authtoken',
            name='usercomponent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authtokens', to='spider_base.UserComponent'),
        ),
        migrations.AlterUniqueTogether(
            name='authtoken',
            unique_together={('usercomponent', 'token')},
        ),
    ]
