# Generated by Django 2.2.1 on 2019-05-26 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0002_20190518_squashed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReverseToken',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=138)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('assignedcontent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reversetokens', to='spider_base.AssignedContent')),
            ],
        ),
    ]
