# Generated by Django 2.2.1 on 2019-05-28 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0003_reversetoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedcontent',
            name='allow_domain_mode',
        ),
        migrations.RemoveField(
            model_name='usercomponent',
            name='allow_domain_mode',
        ),
    ]
