# Generated by Django 2.1 on 2018-08-12 19:22

from django.db import migrations, models
import spkcspider.apps.spider.models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0003_auto_20180812_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponent',
            name='required_passes',
            field=models.PositiveIntegerField(default=spkcspider.apps.spider.models._get_default_amount, help_text='How many protection must be passed? Set greater 0 to enable protection based access'),
        ),
    ]
