# Generated by Django 2.0.6 on 2018-06-18 17:56

from django.db import migrations, models
import spkcspider.apps.spider.helpers


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0003_auto_20180612_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponent',
            name='nonce',
            field=models.SlugField(default=spkcspider.apps.spider.helpers.token_nonce, max_length=270),
        ),
        migrations.AlterField(
            model_name='usercontent',
            name='nonce',
            field=models.SlugField(default=spkcspider.apps.spider.helpers.token_nonce, max_length=270),
        ),
    ]
