# Generated by Django 2.1 on 2018-08-18 13:10

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('spider_base', '0004_auto_20180812_1922'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContent',
            new_name='AssignedContent',
        ),
        migrations.RemoveIndex(
            model_name='assignedcontent',
            name='spider_base_usercom_c9b782_idx',
        ),
        migrations.RemoveIndex(
            model_name='assignedcontent',
            name='spider_base_object__ef74d9_idx',
        ),
    ]
