# Generated by Django 2.0.6 on 2018-06-22 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0005_auto_20180622_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomponent',
            name='public',
            field=models.BooleanField(default=False, help_text='Is public findable?'),
        ),
        migrations.AddField(
            model_name='usercomponent',
            name='required_passes',
            field=models.PositiveIntegerField(default=1, help_text='How many protection passes are required?Set to zero to allow everyone access'),
        ),
    ]
