# Generated by Django 2.2.4 on 2019-08-17 18:14

from django.db import migrations, models
import spkcspider.constants


raise NotImplementedError

class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0005_auto_20190626_1620'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedprotection',
            name='state',
            field=models.CharField(choices=[('off', spkcspider.constants.ProtectionStateType('a')), ('active', spkcspider.constants.ProtectionStateType('b')), ('instant_fail', spkcspider.constants.ProtectionStateType('c'))], default='a', help_text='State of the protection.', max_length=1),
        ),
    ]
