# Generated by Django 2.1 on 2018-08-18 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0005_auto_20180818_1310'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserContentVariant',
            new_name='ContentVariant',
        ),
    ]
