# Generated by Django 2.1.2 on 2018-10-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0006_linkcontent_is_fake'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercomponent',
            name='description',
            field=models.TextField(default='', help_text='Description of user component. Visible if "public".'),
        ),
    ]
