# Generated by Django 2.1.2 on 2018-10-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0007_usercomponent_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkcontent',
            name='is_fake',
        ),
        migrations.AddField(
            model_name='assignedcontent',
            name='fake_id',
            field=models.BigIntegerField(editable=False, null=True),
        ),
    ]
