# Generated by Django 2.1 on 2018-08-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0007_userinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponent',
            name='public',
            field=models.BooleanField(default=False, help_text='Is public? Can be searched?<br/>Note: Field is maybe blocked by assigned content'),
        ),
    ]
