# Generated by Django 2.1 on 2018-08-30 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0008_auto_20180824_0646'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='assignedprotection',
            name='spider_base_usercom_02174c_idx',
        ),
        migrations.RemoveIndex(
            model_name='usercomponent',
            name='spider_base_user_id_3c1312_idx',
        ),
    ]
