# Generated by Django 3.0.1 on 2019-12-30 13:00

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import spkcspider.apps.spider.models.content_extended
import spkcspider.constants.protections


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0009_auto_20190929_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachedBlob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('unique', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('blob', models.BinaryField(blank=True, default=b'', editable=True)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('unique', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to=spkcspider.apps.spider.models.content_extended.get_file_path)),
            ],
        ),
        migrations.CreateModel(
            name='AttachedTimeSpan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=50)),
                ('unique', models.BooleanField(blank=True, default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField()),
                ('stop', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DataContent',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('quota_data', jsonfield.fields.JSONField()),
                ('free_data', jsonfield.fields.JSONField()),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='travelprotection',
            name='associated',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='spider_base.AssignedContent'),
        ),
        migrations.AlterField(
            model_name='assignedprotection',
            name='state',
            field=models.CharField(choices=[(spkcspider.constants.protections.ProtectionStateType['disabled'], 'disabled'), (spkcspider.constants.protections.ProtectionStateType['enabled'], 'enabled'), (spkcspider.constants.protections.ProtectionStateType['instant_fail'], 'instant fail')], default=spkcspider.constants.protections.ProtectionStateType['enabled'], help_text='State of the protection.', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='assignedcontent',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='datacontent',
            name='associated',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='spider_base.AssignedContent'),
        ),
        migrations.AddField(
            model_name='attachedtimespan',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider_base.AssignedContent'),
        ),
        migrations.AddField(
            model_name='attachedfile',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='spider_base.AssignedContent'),
        ),
        migrations.AddField(
            model_name='attachedblob',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spider_base.AssignedContent'),
        ),
        migrations.RemoveField(
            model_name='assignedcontent',
            name='content_type',
        ),
        migrations.AddConstraint(
            model_name='attachedtimespan',
            constraint=models.UniqueConstraint(condition=models.Q(unique=True), fields=('name',), name='AttachedTimeSpan_unique'),
        ),
        migrations.AddConstraint(
            model_name='attachedfile',
            constraint=models.UniqueConstraint(condition=models.Q(('content__isnull', False), ('unique', True)), fields=('name',), name='AttachedFile_unique'),
        ),
        migrations.AddConstraint(
            model_name='attachedblob',
            constraint=models.UniqueConstraint(condition=models.Q(unique=True), fields=('name',), name='AttachedBlobSpan_unique'),
        ),
    ]
