# Generated by Django 3.0.1 on 2019-12-29 23:00

from django.db import migrations


def move_to_datacontent(apps, schema_editor):
    raise


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0010_auto_20191229_2253'),
    ]

    operations = [
        migrations.RunPython(move_to_datacontent),
    ]
