# Generated by Django 3.0.1 on 2019-12-30 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0011_auto_20191230_1305'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LinkContent',
        ),
        migrations.RemoveField(
            model_name='assignedcontent',
            name='object_id',
        ),
        migrations.CreateModel(
            name='LinkContent',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('spider_base.datacontent',),
        ),
    ]
