# Generated by Django 2.1.2 on 2018-11-03 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0011_authtoken_created_by_special_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercomponent',
            name='description',
            field=models.TextField(blank=True, default='', help_text="Description of user component."),
        ),
    ]
