# Generated by Django 2.1.3 on 2018-11-24 20:13

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0012_auto_20181103_0157'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtoken',
            name='extra',
            field=jsonfield.fields.JSONField(blank=True, default={}),
        ),
    ]
