# Generated by Django 2.1.3 on 2018-11-25 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0014_auto_20181125_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprotection',
            name='disallow',
            field=models.ManyToManyField(blank=True, related_name='travel_protected', to='spider_base.UserComponent'),
        ),
    ]
