# Generated by Django 3.0.2 on 2020-01-19 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0014_authtoken_attached_to_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=138, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\A[-a-zA-Z0-9_]+\\Z', 'Enter a valid token.', 'invalid_token')]),
        ),
    ]
