# Generated by Django 3.0.3 on 2020-02-21 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0015_auto_20200119_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authtoken',
            name='attached_to_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attached_tokens', to='spider_base.AssignedContent'),
        ),
    ]
