# Generated by Django 2.1.3 on 2018-12-01 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0015_auto_20181125_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelprotection',
            name='is_fake',
            field=models.BooleanField(default=False),
        ),
    ]
