# Generated by Django 2.2.1 on 2019-05-05 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0017_auto_20190504_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcontent',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=138, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\A[-a-zA-Z0-9_]+\\Z', 'Enter a valid token.', 'invalid_token')]),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.CharField(db_index=True, max_length=138, unique=True, validators=[django.core.validators.RegexValidator('\\A[-a-zA-Z0-9_]+\\Z', 'Enter a valid token.', 'invalid_token')]),
        ),
        migrations.AlterField(
            model_name='usercomponent',
            name='token',
            field=models.CharField(blank=True, db_index=True, max_length=138, null=True, unique=True, validators=[django.core.validators.RegexValidator('\\A[-a-zA-Z0-9_]+\\Z', 'Enter a valid token.', 'invalid_token')]),
        ),
    ]
