# Generated by Django 2.1.4 on 2018-12-30 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0017_auto_20181202_2249'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentFeature',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='usercomponent',
            name='avail_features',
            field=models.CharField(default=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='authtoken',
            name='token',
            field=models.SlugField(max_length=136, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='authtoken',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='usercomponent',
            name='features',
            field=models.ManyToManyField(blank=True, related_name='supports', to='spider_base.ComponentFeature'),
        ),
    ]
