# Generated by Django 2.2.1 on 2019-05-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0020_auto_20190509_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='travelprotection',
            name='active',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='travelprotection',
            name='login_protection',
            field=models.CharField(choices=[('a', 'Hide'), ('b', 'Hide if triggered'), ('e', 'Disable login'), ('c', 'Wipe'), ('d', 'Wipe User')], default='a', max_length=1),
        ),
    ]
