# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 08:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spiderbroker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='protected_by',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brokers', to=settings.SPIDERPK_USERCOMPONENT_MODEL),
        ),
    ]
