# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 08:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('spiderbroker', '0002_auto_20171103_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='broker',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
