# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-03 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderbroker', '0003_auto_20171103_0825'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='broker',
            name='extra',
        ),
        migrations.AddField(
            model_name='broker',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
