# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderpk', '0002_auto_20171103_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='key',
            field=models.TextField(),
        ),
    ]
