# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-12 12:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import spkbspider.apps.spiderkeys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.SPIDERUCS_USERCOMPONENT_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(validators=[spkbspider.apps.spiderkeys.models.valid_pkey_properties])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(max_length=400)),
                ('hash', models.CharField(editable=False, max_length=128, unique=True)),
                ('protected_by', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publickeys', to=settings.SPIDERUCS_USERCOMPONENT_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'swappable': 'SPIDERPK_PUBLICKEY_MODEL',
            },
        ),
    ]
