# Generated by Django 2.1.7 on 2019-02-25 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_base', '0008_auto_20190225_2034'),
        ('spider_tags', '0005_spidertag_updateable_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spidertag',
            name='updateable_by',
        ),
        migrations.AddField(
            model_name='spidertag',
            name='updateable_by',
            field=models.ManyToManyField(blank=True, to='spider_base.ReferrerObject'),
        ),
    ]
