# Generated by Django 3.0.1 on 2019-12-30 14:42

from django.db import migrations


def fix_usertags(apps, schema_editor):
    UserTagLayout = apps.get_model("spider_tags", "UserTagLayout")
    TagLayout = apps.get_model("spider_tags", "TagLayout")

    for d in UserTagLayout.objects.all():
        layout = TagLayout.objects.get(id=d.free_data["tmp_layout_id"])
        layout.usertag = d.associated
        del d.free_data["tmp_layout_id"]
        d.clean()
        d.save(update_fields=["free_data"])


class Migration(migrations.Migration):

    dependencies = [
        ('spider_tags', '0010_auto_20191230_1353'),
    ]

    operations = [
        migrations.RunPython(fix_usertags),
    ]
