# Generated by Django 2.0.5 on 2018-06-10 12:23

from django.db import migrations, models
import spkcspider.apps.spider_keys.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('key', models.TextField(validators=[spkcspider.apps.spider_keys.models.valid_pkey_properties])),
                ('note', models.TextField(blank=True, default='', max_length=100)),
                ('hash', models.CharField(editable=False, max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
