# Generated by Django 2.0.5 on 2018-06-07 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_keys', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publickey',
            name='note',
            field=models.TextField(blank=True, default='', max_length=100),
        ),
    ]
