# Generated by Django 2.0.6 on 2018-06-18 19:05

from django.conf import settings
from django.db import migrations, models
import spkcspider.apps.spider_filets.models


class Migration(migrations.Migration):

    dependencies = [
        ('spider_filets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filefilet',
            name='file',
            field=models.FileField(upload_to=spkcspider.apps.spider_filets.models.get_file_path),
        ),
        migrations.AlterField(
            model_name='textfilet',
            name='edit_allowed',
            field=models.ManyToManyField(blank=True, related_name='_textfilet_edit_allowed_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
